name: Upload to pypi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # accept all tags of the format vX.X.X

jobs:
  deploy:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository == 'gutsche-lab/blik'
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pep517
    - name: Build Distribution
      run: |
        python -m pep517.build .
    - name: Publish PyPI Package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
